### ISSUE TITLE
feat: transform commonjs to esm

### ISSUE THREAD

**Issue by hyrious** [hyrious/esbuild-plugin-commonjs#2]
I came up with a super easy way of doing this instead of going "syntheticNamedExports". To be clear I just want to replicate the node17 behavior: use cjs-module-lexer to support partial of the cjs modules. The transformed module will be like:
```js
var exports = {}, module = {exports}
// have to use { block } to prevent names conflict
{
  // original code
}
export default module.exports
// analyzed possible named exports
export var useState = module.exports.useState
...
```

The downside is obvious: some modules will cause error at runtime when it doesn't follow the pattern. But the advantage is we can reduce some verbosing code about `__commonJS`. I can make this transformation optional.

Those `require`s still need the trick in this repo. But I want to add additional info here:

```js
try { require("x") } catch {}
```

Code like this won't be transformed to `import` statement because esbuild allowed this pattern and it won't warn about it. Frankly speaking, even "require is undefined" won't cause error at runtime when it was caught like this.

**Comment by hyrious** [comment]
[Preview Link](https://hyrious.me/esbuild-repl/?version=0.14.21&mode=build&modules=%5B%5B%22main.js%22%2C%22import+%7B+a+%7D+from+%27.%2Fb%27%5Cnconsole.log%28a%29%22%2C1%5D%2C%5B%22b.js%22%2C%22var+exports+%3D+%7B%7D%2C+module+%3D+%7Bexports%7D%5Cn%7B+exports.a+%3D+1+%7D%5Cnexport+default+module.exports%5Cnexport+var+a+%3D+module.exports.a%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Atrue%7D) if the proposal of this issue come true.

**Comment by hyrious** [comment]
🚢 0.2.0
I'll keep this issue open if there be any improvements to the conversion or strong reasons to remove this feature.

**Comment by v1rtl** [comment]
I don't understand whether this feature is already a part of the plugin or there's an intent to ship it

I'm building a CLI and I want to bundle all the deps, and right now it's impossible with ESM and CJS dependencies

can I activate the feature anyhow rn?

**Comment by hyrious** [comment]
@talentlessguy Yes it is shipped and documented in README. To activate it, an optional dependency `cjs-module-lexer` must be installed first, then enable `transform` in the plugin's options. Basically:

```console
$ npm add -D cjs-module-lexer
```

```js
commonjs({ transform: true })
```

However during my early tests, the transform:

- is not always safe to produce runnable code. You need to test the bundle after using it.
- doesn't erase many codes.

There're some more options to fine-tune the tranforming process. You will need to look at the README and comments on the TypeScript interfaces.

> ...I want to bundle all the deps.

esbuild can bundle commonjs modules without this plugin. Maybe you're looking at the wrong tool to solve your problem. You can post some more details or reproduction about your issue so that we can investigate it.

**Comment by v1rtl** [comment]
@hyrious enabling transform: true breaks with ESM imports

this is my config:

```js
import { commonjs } from "@hyrious/esbuild-plugin-commonjs";
import { build } from "esbuild";
import { builtinModules } from "node:module";

await build({
  entryPoints: ["src/cli.ts"],
  bundle: true,
  format: "esm",
  external: [...builtinModules, ...builtinModules.map(m => `node:${m}`)],
  outfile: "dist/cli.js",
  plugins: [commonjs({transform: true})],
}).catch(() => process.exit(1));
```

This yields these errors:

```
The plugin "commonjs" was triggered by this import

    src/utils/ipfs.ts:7:63:
      7 │ import { CAREncoderStream, createDirectoryEncoderStream } from 'ipfs-car'
        ╵                                                                ~~~~~~~~~~

✘ [ERROR] Parse error @7:1:8 [plugin commonjs]

    node_modules/.pnpm/@hyrious+esbuild-plugin-commonjs@0.2.5_cjs-module-lexer@2.1.0_esbuild@0.25.2/node_modules/@hyrious/esbuild-plugin-commonjs/index.js:246:23:
      246 │           cjsExports = parseCJS(contents);
          ╵                        ^

    at parse (file:///home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/cjs-module-lexer@2.1.0/node_modules/cjs-module-lexer/dist/lexer.mjs:2:381)
    at /home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/@hyrious+esbuild-plugin-commonjs@0.2.5_cjs-module-lexer@2.1.0_esbuild@0.25.2/node_modules/@hyrious/esbuild-plugin-commonjs/index.js:246:24
    at async requestCallbacks.on-load (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:1277:22)
    at async handleRequest (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:648:11)

  This error came from the "onLoad" callback registered here:

    node_modules/.pnpm/@hyrious+esbuild-plugin-commonjs@0.2.5_cjs-module-lexer@2.1.0_esbuild@0.25.2/node_modules/@hyrious/esbuild-plugin-commonjs/index.js:219:6:
      219 │       onLoad({ filter }, async (args) => {
          ╵       ~~~~~~

    at setup (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/@hyrious+esbuild-plugin-commonjs@0.2.5_cjs-module-lexer@2.1.0_esbuild@0.25.2/node_modules/@hyrious/esbuild-plugin-commonjs/index.js:219:7)
    at handlePlugins (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:1151:21)
    at buildOrContextImpl (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:874:5)
    at Object.buildOrContext (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:700:5)
    at /home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:2035:15
    at new Promise (<anonymous>)
    at Object.build (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:2034:25)
    at build (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:1885:51)
    at file:///home/v1rtl/Coding/stauro/blumen/esbuild.config.js:5:7

  The plugin "commonjs" was triggered by this import

    src/providers/ipfs/storacha.ts:14:22:
      14 │ import * as HTTP from '@ucanto/transport/http'
         ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Parse error @7:1:8 [plugin commonjs]

    node_modules/.pnpm/@hyrious+esbuild-plugin-commonjs@0.2.5_cjs-module-lexer@2.1.0_esbuild@0.25.2/node_modules/@hyrious/esbuild-plugin-commonjs/index.js:246:23:
      246 │           cjsExports = parseCJS(contents);
          ╵                        ^

    at parse (file:///home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/cjs-module-lexer@2.1.0/node_modules/cjs-module-lexer/dist/lexer.mjs:2:381)
    at /home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/@hyrious+esbuild-plugin-commonjs@0.2.5_cjs-module-lexer@2.1.0_esbuild@0.25.2/node_modules/@hyrious/esbuild-plugin-commonjs/index.js:246:24
    at async requestCallbacks.on-load (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:1277:22)
    at async handleRequest (/home/v1rtl/Coding/stauro/blumen/node_modules/.pnpm/esbuild@0.25.2/node_modules/esbuild/lib/main.js:648:11)

  This error came from the "onLoad" callback registered here:

    node_modules/.pnpm/@hyrious+esbuild-plugin-commonjs@0.2.5_cjs-module-lexer@2.1.0_esbuild@0.25.2/node_modules/@hyrious/esbuild-plugin-commonjs/index.js:219:6:
```

It treats all package as CJS, instead of only CJS ones

**Comment by v1rtl** [comment]
I managed to make it build by explicitly listing all ESM packages:

```js
import { commonjs } from "@hyrious/esbuild-plugin-commonjs";
import { build } from "esbuild";
import { builtinModules } from "node:module"

const esmPackages = [
  "spektr",
  'ipfs-car',
  '@stauro/',
  '@ipld/car',
  'uint8arrays',
  'multiformats',
  '@web3-storage/',
  '@ucanto/',
  '@ipld/',
  'cborg',
  '@noble/',
  '@scure/',
  'sync-multihash-sha2',
  'carstream',
  'uint8arraylist',
  '@perma/',
  'actor',
  'p-retry',
  'is-network-error',
  'viem',
  'ox',
  'isows',
  'abitype'
]

await build({
  entryPoints: ["src/cli.ts"],
  bundle: true,
  format: "esm",
  target: 'es2023',
  platform:'node',
  external: [...builtinModules, ...builtinModules.map(m => `node:${m}`)],
  outfile: "dist/cli.js",
  plugins: [commonjs({transform: (path) => {
    return !esmPackages.some(pkg => path.includes(pkg))
  }})],
}).catch(() => process.exit(1))
```

but it makes star imports resolve to `undefined`:

```js
  const resolveSymlink = __importStar(resolve_symlink_default);
  const invokeCallback = __importStar(import_invoke_callback.default);
  const walkDirectory = __importStar(walk_directory_default);
```

```
file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:63271
      this.callbackInvoker = invokeCallback.build(options, this.isSynchronous);
                                            ^

TypeError: invokeCallback.build is not a function
    at new Walker2 (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:63271:45)
    at callback2 (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:63355:18)
    at file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:63348:7
```

**Comment by hyrious** [comment]
> ```js
>   external: [...builtinModules, ...builtinModules.map(m => `node:${m}`)],
> ```

According to this line, I assume you only have some issue on bundling commonjs modules which uses some Node.js builtin modules. If that's the case, you don't have to use the transform option. Simply use:

```js
plugins: [commonjs()]
```

should be ok.

- - -

Note to myself:

The `__importStar()` issue is more complicated. It exists in some commonjs modules which are adopting the babel style (or `tsc`'s default behavior) when importing external modules:

```js
// entry.js
__importStar(require('./another-file'))
```

This line will not be transformed by my plugin since it is not matched by the `transform` option. However, the `./another-file` will be transformed from commonjs to esm and will mess up the interop helpers:

```js
// another-file.js
export const build = 1

// entry.js
var mod = __importStar(require('./another-file')) // now requiring an ESM file!
```

&darr; &darr; &darr;

```js
// bundle.js
var require_another_file = () => ({ build: 1 });
var another_file = __toESM(require_another_file())
var mod = __importStar(another_file)
```

The interop helpers:

`__toESM`: Wraps a module object and properly handles `__esModule`'s semantic. After this helper the module will NOT contain the `__esModule` field.

`__importStar`: **Wraps a module object and properly handles `__esModule`'s semantic.** Notice how this work cannot be done twice on the same object.

So when I want to transform a commonjs module to ESM, it has chance to break when the cjs file was requiring by another cjs file.

One possible solution is to slightly rewrite the `__toESM` helper function to add `__esModule` on the final object. For example:

```js
var __toESM = (mod6, isNodeMode, target) => {
  var result = (target = mod6 != null ? __create(__getProtoOf(mod6)) : {}, __copyProps(
    isNodeMode || !mod6 || !mod6.__esModule ? __defProp(target, "default", { value: mod6, enumerable: true }) : target,
    mod6
  ))
  if (!result.__esModule) __defProp(result, '__esModule', { value: true });
  return result
};
```

**Comment by v1rtl** [comment]
just using `commonjs()` leads to this:

```sh
file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:5065
      return builder_1.Builder;
                       ^

TypeError: Cannot read properties of undefined (reading 'Builder')
    at Object.get [as fdir] (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:5065:24)
    at Object.get [as fdir] (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:25:48)
    at crawl (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:38732:31)
    at glob (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:38744:10)
    at walk2 (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:38753:29)
    at packAction (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:39071:32)
    at deployAction (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:39118:61)
    at cli.command.description [as action] (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:39344:43)
    at handleActionWithHelp (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:5366:16)
    at _CLI.handle (file:///home/v1rtl/Coding/stauro/blumen/dist/cli.js:5511:14)

Node.js v22.14.0
```

which happens here:

```js
// node_modules/.pnpm/fdir@6.4.4_picomatch@4.0.2/node_modules/fdir/dist/index.js
var require_dist = __commonJS({
  "node_modules/.pnpm/fdir@6.4.4_picomatch@4.0.2/node_modules/fdir/dist/index.js"(exports2) {
    var import_builder = __toESM(require_builder());
    var import_types2 = __toESM(require_types());
    var __createBinding = exports2 && exports2.__createBinding || (Object.create ? function(o, m, k, k2) {
      if (k2 === void 0) k2 = k;
      var desc = Object.getOwnPropertyDescriptor(m, k);
      if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
        desc = { enumerable: true, get: function() {
          return m[k];
        } };
      }
      Object.defineProperty(o, k2, desc);
    } : function(o, m, k, k2) {
      if (k2 === void 0) k2 = k;
      o[k2] = m[k];
    });
    var __exportStar = exports2 && exports2.__exportStar || function(m, exports3) {
      for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports3, p)) __createBinding(exports3, m, p);
    };
    Object.defineProperty(exports2, "__esModule", { value: true });
    exports2.fdir = void 0;
    var builder_1 = import_builder.default;
    Object.defineProperty(exports2, "fdir", { enumerable: true, get: function() {
      return builder_1.Builder;
    } });
    __exportStar(import_types2.default, exports2);
  }
});
```

**Comment by hyrious** [comment]
I see. This was because the "require to import" logic being applied to a babel-style file (in this case `node_modules/.pnpm/fdir@6.4.4_picomatch@4.0.2/node_modules/fdir/dist/index.js`), which results in a mess around interop helpers. The best way to handle those files in my opinion is to leave them as-is.

You can try updating your build script like this:

```js
const external = [...builtinModules, ...builtinModules.map(m => `node:${m}`)]

await build({
  ...,
  external,
  plugins: [commonjs(
    // Only transform things like `require('fs')` to `import 'fs'`.
    // Any other `require`s are not touched.
    { ignore: path => !external.includes(path) }
  )],
}).catch(() => process.exit(1))
```

So it messes up a lot of things when dealing with babel-style code. Looking back to my initial purpose: eliminating `__require` in the bundle. I guess only external paths could have a chance to become a `__require('path')`. So maybe I should only handle them by default instead of handle every require calls.
